spring:
  profiles:
    active: local
    group:
      local: local, common
      blue: blue, common
      green: green, common

server:
  env: blue

---

## local 서버 실행 환경
spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: http://localhost/login/oauth2/code/naver

server:
  port: 8080
  serverAddress: localhost

serverName: local_server

---

## blue 서버 실행 환경
spring:
  config:
    activate:
      on-profile: blue
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: http://16.184.57.174/login/oauth2/code/naver
server:
  port: 8080
  serverAddress: 16.184.57.174

serverName: blue_server

---

## green 서버 실행 환경
spring:
  config:
    activate:
      on-profile: green
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: http://16.184.57.174:8080/login/oauth2/code/naver
server:
  port: 8081
  serverAddress: 16.184.57.174

serverName: green_server

---

spring:
  config:
    activate:
      on-profile: common

  datasource:
    url: jdbc:mysql://db:3306/dadokim
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
    hikari:
      initializationFailTimeout: 0   # DB 준비 안됐으면 계속 재시도
      connectionTimeout: 30000       # 30초까지 대기

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ZHohTJRXUuS1EBagjWfi
            client-secret: RWbPqFkJ2a
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION}

# AI API Keys (최상위 레벨)
geminiapi:
  key: ${GEMINI_API_KEY}

chatkey: ${GPT_API_KEY}

# 카카오 REST API 키 주입
kakao:
  rest-api-key: ${KAKAO_API_KEY}